### ISSUE TITLE
Feature group events

### ISSUE THREAD

**Issue by buepro** [derhansen/sf_event_mgt_indexer#12]
We have a use case where predefined groups of users exist. Users in a group can participate in events. The admin can create events and assign them to groups or assign the event to groups. In a matrix view the registration state is shown for each user (not registered yet, registered, registration canceled) where horizontaly the events are listed chronologically and veryically the users are listed (by group).

![GroupEvents](https://user-images.githubusercontent.com/37214997/122181227-76913000-ce89-11eb-871d-85354dc0a670.jpg)
Image: Extending `sf_event_mgt` with a separate extension to manage group events

Do you think this could be useful in general? In this case I could create a feature branch hence the functionality wouldn't need to be provided by a separate extension (as shown in the above image).

**Comment by derhansen** [comment]
Thanks for your feature suggestion. Interesting use case, but I do not think this would git into the extension in general. I prefer to keep the extension complexity as simple as possible, since extension maintenance (including updates to new major TYPO3 versions) is most likely still a one man show. So I suggest to create an extension that extends sf_event_mgt and I will add a link to it in the main documentation.

BTW: You used the wrong issue tracker - this https://github.com/derhansen/sf_event_mgt the main repository of the extension.
