### ISSUE TITLE
Add incremental indexing

### ISSUE THREAD

**Issue by ste101** [derhansen/sf_event_mgt_indexer#19]
Incremental indexing is possible since ke_search 3.8.0.

This indexer does not show the duration (column time).

**Comment by derhansen** [comment]
I checked how to implement this and obviously, this is not documented at all - see https://docs.typo3.org/p/tpwd/ke_search/4.6/en-us/Indexing/IndexerTypes/Custom.html

But I see, that custom indexers now obviously must extend  `IndexerBase`, which however requires refactoring für the event indexer, since both have a `getPidList` with different signatures.

Will have a look at this "some time", but it has no priority. Feel free to provide a PR if you want.

**Comment by derhansen** [comment]
OK, now I found some documentation. 

I will not add incremental indexing for events due to the mentioned drawbacks (see https://docs.typo3.org/p/tpwd/ke_search/4.6/en-us/Indexing/Index.html?highlight=incremental#full-indexing-and-incremental-indexing).  

But the event indexer now extends `IndexerBase` so at least the indexing time is shown.

**Comment by derhansen** [comment]
Released version 3.0.2.

**Comment by ste101** [comment]
Thank you for the new version.
I like incremental indexing very much.
Don't you think that it is up to the user if the drawbacks are relevant or not and if he is using incremental indexing or not?

**Comment by derhansen** [comment]
Yes, that decision may be up to the user. Can you provide a PR for the feature?
